### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by torotil** [moreonion/open-parliament#2]
I get the following error when running the parse command.

```
2019-08-20 11:53:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.parlament.gv.at/WWER/PAD_05485/index.shtml#tab-Ausschuesse> (referer: https://www.parlament.gv.at/WWER/PAD_05485/)
Traceback (most recent call last):
  File "/home/roman/code/e2t-data/.venv/lib64/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/roman/code/e2t-data/.venv/lib64/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/roman/code/e2t-data/.venv/lib64/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/roman/code/e2t-data/.venv/lib64/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/roman/code/e2t-data/.venv/lib64/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/roman/code/e2t-data/.venv/src/open-parliament/spider.py", line 73, in parse_committees
    mp.update(committee_parser.parse())
  File "/home/roman/code/e2t-data/.venv/src/open-parliament/open_parliament/parsers.py", line 365, in parse
    position = p.previousSibling.previousSibling.text.strip()
  File "/home/roman/code/e2t-data/.venv/lib64/python3.6/site-packages/bs4/element.py", line 646, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'Comment' object has no attribute 'text'
```

**Comment by m-strasser** [comment]
Fixed by https://github.com/moreonion/open-parliament/pull/3
